site_name: Chaos League Wiki
site_description: Unofficial Wiki of the Chaos League Game made by DoodleChaos.
site_author: Andre_601

site_url: 'https://chaosleaguewiki.github.io'

copyright: 'Everything is licensed under <a href="https://github.com/chaosleaguewiki/chaosleaguewiki.github.io/blob/main/LICENSE" target="_blank" rel="nofollow">MIT</a> unless stated otherwise.'

docs_dir: docs/

repo_name: Wiki Source
repo_url: https://github.com/chaosleaguewiki/chaosleaguewiki.github.io

nav:
  - index.md
  - Chat Commands:
    - chat-commands/index.md
    - chat-commands/twitch.md
    #- chat-commands/youtube.md
  - Game Mechanics:
    - mechanics/index.md
    - mechanics/attacking-the-king.md
  - Twitch Minigames:
    - twitch-minigames/index.md
    - Common:
      - twitch-minigames/common/bounce-house.md
      - twitch-minigames/common/danger-zone.md
      - twitch-minigames/common/how-low-can-you-go.md
      - twitch-minigames/common/quip-battle.md
    - Rare:
      - twitch-minigames/rare/stonks.md
    - Epic:
      - twitch-minigames/epic/royal-execution.md
    - Legendary:
      - twitch-minigames/legendary/hole-in-one.md
  - changelog.md

theme:
  name: material
  custom_dir: '.theme'
  icon:
    logo: 'fontawesome/solid/book'
    repo: 'octicons/mark-github-16'
    admonition:
      note: octicons/pencil-16
      abstract: octicons/multi-select-16
      info: octicons/info-16
      tip: octicons/light-bulb-16
      success: octicons/check-circle-16
      question: octicons/question-16
      warning: octicons/stop-16
      failure: octicons/x-circle-16
      danger: octicons/alert-16
      bug: octicons/bug-16
      example: octicons/list-unordered-16
      quote: octicons/comment-16
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      toggle:
        icon: octicons/sun-24
        name: 'Switch to Dark theme'
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      toggle:
        icon: octicons/moon-24
        name: 'Switch to Light theme'
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top

extra_css:
  - assets/stylesheet/style.css

watch:
  - .snippets

plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - meta
  - abbr
  - pymdownx.superfences
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: '.snippets'
      auto_append:
        - 'game-terminology.md'
  - pymdownx.highlight
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
        - wiki
  - pymdownx.blocks.details:
  - pymdownx.blocks.tab:
      alternate_style: true