site_name: Chaos League Wiki
site_description: Unofficial Wiki of the Chaos League Game made by DoodleChaos.
site_author: Andre_601

site_url: 'https://chaosleaguewiki.github.io'

copyright: |-
  Everything is licensed under <a href="https://github.com/chaosleaguewiki/chaosleaguewiki.github.io/blob/main/LICENSE" target="_blank" rel="nofollow">MIT</a> unless stated otherwise.<br>
  <br>
  <a href="#__consent">Manage Cookies</a>

docs_dir: docs/

repo_name: Wiki Source
repo_url: https://github.com/chaosleaguewiki/chaosleaguewiki.github.io

nav:
  - index.md
  - Chat Commands:
    - chat-commands/index.md
    - chat-commands/twitch.md
    #- chat-commands/youtube.md
  - Game Mechanics:
    - mechanics/index.md
    - mechanics/attacking-the-king.md
    - mechanics/death-ball.md
    - mechanics/earning-gold.md
    - mechanics/gold-tile.md
    - mechanics/points-multiplier.md
    - mechanics/queue-system.md
    - mechanics/rebellion.md
    - mechanics/recruiting.md
    - mechanics/water-and-lava-bucket.md
  - Tiles:
    - Twitch:
      - twitch-tiles/index.md
      - Minigames:
        - twitch-tiles/minigames/bounce-house.md
        - twitch-tiles/minigames/chaos-plinko.md
        - twitch-tiles/minigames/danger-zone.md
        - twitch-tiles/minigames/forked-frenzy.md
        - twitch-tiles/minigames/hole-in-one.md
        - twitch-tiles/minigames/how-low-can-you-go.md
        - twitch-tiles/minigames/ouroboros.md
        - twitch-tiles/minigames/quip-battle.md
        - twitch-tiles/minigames/royal-execution.md
        - twitch-tiles/minigames/stonks.md
        - twitch-tiles/minigames/zero-or-hero.md
        - twitch-tiles/minigames/zobm-says.md
      - Shops:
        - twitch-tiles/shops/bubble-color-shop.md
        - twitch-tiles/shops/text-color-shop.md
        - twitch-tiles/shops/trail-shop.md
    - YouTube:
      - youtube-minigames/index.md
      - Common:
        - youtube-minigames/common/bounce-house.md
        - youtube-minigames/common/how-low-can-you-go.md
  - Changelog:
      - changelog/index.md
      - v3:
        - Alpha:
          - changelog/cl3/alpha/v0.28-alpha.md
          - changelog/cl3/alpha/v0.27-alpha.md
          - changelog/cl3/alpha/v0.26-alpha.md
          - changelog/cl3/alpha/v0.25-alpha.md
          - changelog/cl3/alpha/v0.24-alpha.md
          - changelog/cl3/alpha/v0.23-alpha.md
          - changelog/cl3/alpha/v0.22-alpha.md
          - changelog/cl3/alpha/v0.21-alpha.md
          - changelog/cl3/alpha/v0.20-alpha.md
          - changelog/cl3/alpha/v0.19-alpha.md
          - changelog/cl3/alpha/v0.18-alpha.md
          - changelog/cl3/alpha/v0.17-alpha.md
          - changelog/cl3/alpha/v0.16-alpha.md
          - changelog/cl3/alpha/v0.15-alpha.md
          - changelog/cl3/alpha/v0.14-alpha.md
          - changelog/cl3/alpha/v0.13-alpha.md
          - changelog/cl3/alpha/v0.12-alpha.md
          - changelog/cl3/alpha/v0.11-alpha.md
          - changelog/cl3/alpha/v0.10-alpha.md
          - changelog/cl3/alpha/v0.9-alpha.md
          - changelog/cl3/alpha/v0.8-alpha.md
          - changelog/cl3/alpha/v0.7-alpha.md
          - changelog/cl3/alpha/v0.6-alpha.md
          - changelog/cl3/alpha/v0.5-alpha.md
          - changelog/cl3/alpha/v0.4-alpha.md
          - changelog/cl3/alpha/v0.3-alpha.md
          - changelog/cl3/alpha/v0.2-alpha.md
          - changelog/cl3/alpha/v0.1-alpha.md
  - Meta:
    - meta/index.md
    - Filters:
      - meta/filters/index.md
      - meta/filters/markdownify.md
    - Macros:
      - meta/macros/index.md
      - meta/macros/image.md
      - meta/macros/game.md
      - meta/macros/misc.md
      - meta/macros/utils.md
    - Snippets:
      - meta/snippets/index.md
      - meta/snippets/commands.md
      - meta/snippets/games.md
      - meta/snippets/game-terminology.md
      - meta/snippets/unreleased.md
    - Terminology:
      - meta/terminology/index.md

theme:
  name: material
  custom_dir: '.theme'
  favicon: assets/images/favicons/android-chrome-512x512.png
  icon:
    logo: 'fontawesome/solid/book'
    repo: 'octicons/mark-github-16'
    admonition:
      note: octicons/pencil-16
      abstract: octicons/multi-select-16
      info: octicons/info-16
      tip: octicons/light-bulb-16
      success: octicons/check-circle-16
      question: octicons/question-16
      warning: octicons/stop-16
      failure: octicons/x-circle-16
      danger: octicons/alert-16
      bug: octicons/bug-16
      example: octicons/list-unordered-16
      quote: octicons/comment-16
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      toggle:
        icon: octicons/sun-24
        name: 'Switch to Dark theme'
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      toggle:
        icon: octicons/moon-24
        name: 'Switch to Light theme'
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - content.tooltips

extra:
  announcement: |
    We are looking for contributors!<br>
    If you have experience with Chaos League, consider contributing to this wiki <a href="https://github.com/chaosleaguewiki/chaosleaguewiki.github.io" target="_blank" rel="nofollow">on GitHub!</a>
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our wiki and whether users find what
      they're searching for. With your consent, you're helping us to make our
      wiki better.
    actions:
      - accept
      - reject
      - manage

extra_css:
  - assets/stylesheet/style.css
  - assets/stylesheet/admonition.css

watch:
  - .snippets
  - .theme

validation:
  links:
    absolute_links: ignore # Ignore Absolute links being used.

plugins:
  - search
  - glightbox
  - redirects:
      redirect_maps:
        # Simon Says redirect
        "twitch-tiles/minigames/simon-says.md": "twitch-tiles/minigames/zobm-says.md"
        # Changelog alpha pages before move
        "changelog/cl3/v0.25-alpha.md": "changelog/cl3/alpha/v0.25-alpha.md"
        "changelog/cl3/v0.24-alpha.md": "changelog/cl3/alpha/v0.24-alpha.md"
        "changelog/cl3/v0.23-alpha.md": "changelog/cl3/alpha/v0.23-alpha.md"
        "changelog/cl3/v0.22-alpha.md": "changelog/cl3/alpha/v0.22-alpha.md"
        "changelog/cl3/v0.21-alpha.md": "changelog/cl3/alpha/v0.21-alpha.md"
        "changelog/cl3/v0.20-alpha.md": "changelog/cl3/alpha/v0.20-alpha.md"
        "changelog/cl3/v0.19-alpha.md": "changelog/cl3/alpha/v0.19-alpha.md"
        "changelog/cl3/v0.18-alpha.md": "changelog/cl3/alpha/v0.18-alpha.md"
        "changelog/cl3/v0.17-alpha.md": "changelog/cl3/alpha/v0.17-alpha.md"
        "changelog/cl3/v0.16-alpha.md": "changelog/cl3/alpha/v0.16-alpha.md"
        "changelog/cl3/v0.15-alpha.md": "changelog/cl3/alpha/v0.15-alpha.md"
        "changelog/cl3/v0.14-alpha.md": "changelog/cl3/alpha/v0.14-alpha.md"
        "changelog/cl3/v0.13-alpha.md": "changelog/cl3/alpha/v0.13-alpha.md"
        "changelog/cl3/v0.12-alpha.md": "changelog/cl3/alpha/v0.12-alpha.md"
        "changelog/cl3/v0.11-alpha.md": "changelog/cl3/alpha/v0.11-alpha.md"
        "changelog/cl3/v0.10-alpha.md": "changelog/cl3/alpha/v0.10-alpha.md"
        "changelog/cl3/v0.9-alpha.md": "changelog/cl3/alpha/v0.9-alpha.md"
        "changelog/cl3/v0.8-alpha.md": "changelog/cl3/alpha/v0.8-alpha.md"
        "changelog/cl3/v0.7-alpha.md": "changelog/cl3/alpha/v0.7-alpha.md"
        "changelog/cl3/v0.6-alpha.md": "changelog/cl3/alpha/v0.6-alpha.md"
        "changelog/cl3/v0.5-alpha.md": "changelog/cl3/alpha/v0.5-alpha.md"
        "changelog/cl3/v0.4-alpha.md": "changelog/cl3/alpha/v0.4-alpha.md"
        "changelog/cl3/v0.3-alpha.md": "changelog/cl3/alpha/v0.3-alpha.md"
        "changelog/cl3/v0.2-alpha.md": "changelog/cl3/alpha/v0.2-alpha.md"
        "changelog/cl3/v0.1-alpha.md": "changelog/cl3/alpha/v0.1-alpha.md"
        # twitch-minigames index redirect
        'twitch-minigames/index.md': 'twitch-tiles/index.md'
        # Common tiles redirects
        'twitch-minigames/common/bounce-house.md': 'twitch-tiles/minigames/bounce-house.md'
        'twitch-minigames/common/danger-zone.md': 'twitch-tiles/minigames/danger-zone.md'
        'twitch-minigames/common/how-low-can-you-go.md': 'twitch-tiles/minigames/how-low-can-you-go.md'
        'twitch-minigames/common/ouroboros.md': 'twitch-tiles/minigames/ouroboros.md'
        'twitch-minigames/common/quip-battle.md': 'twitch-tiles/minigames/quip-battle.md'
        'twitch-minigames/common/zero-or-hero.md': 'twitch-tiles/minigames/zero-or-hero.md'
        # Rare tiles redirects
        'twitch-minigames/rare/chaos-plinko.md': 'twitch-tiles/minigames/chaos-plinko.md'
        'twitch-minigames/rare/forked-frenzy.md': 'twitch-tiles/minigames/forked-frenzy.md'
        'twitch-minigames/rare/royal-execution.md': 'twitch-tiles/minigames/royal-execution.md'
        'twitch-minigames/rare/stonks.md': 'twitch-tiles/minigames/stonks.md'
        # Epic tiles redirects
        'twitch-minigames/epic/bubble-color-shop.md': 'twitch-tiles/shops/bubble-color-shop.md'
        'twitch-minigames/epic/text-color-shop.md': 'twitch-tiles/shops/text-color-shop.md'
        'twitch-minigames/epic/trail-shop.md': 'twitch-tiles/shops/trail-shop.md'
        # Legendary tiles redirects
        'twitch-minigames/legendary/hole-in-one.md': 'twitch-tiles/minigames/hole-in-one.md'
  - git-revision-date-localized:
      enabled: !ENV [GIT_COMMITTER_ENABLED, false]
      enable_creation_date: true
      exclude:
        - changelog/index.md
  - git-committers:
      enabled: !ENV [GIT_COMMITTER_ENABLED, false]
      repository: chaosleaguewiki/chaosleaguewiki.github.io
      branch: main
      token: !ENV [COMMITTER_TOKEN]
      exclude:
        - docs/changelog/index.md
  - macros:
      module_name: .hooks/macros
      include_dir: .snippets/macros

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - meta
  - abbr
  - md_in_html
  - pymdownx.superfences
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: '.snippets'
      auto_append:
        - 'game-terminology.md'
        - 'games.md'
        - 'commands.md'
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
        - wiki
        - wip
        - removed
  - pymdownx.blocks.details:
  - pymdownx.blocks.tab:
      alternate_style: true
